package com.umer.andriod.retrofit_network_sample.network;

/**
 * Created by Fahid on 6/7/2016.
 */
public enum RequestCode {
    LOGIN_REQUEST_CODE,
    UI_LIST_REQUEST_CODE,
    OFFICE_SETTINGS_REQUEST_CODE,
    APP_VERSION_REQUEST_CODE,
    READ_USER_SIGNATURE_REQUEST_CODE,
    CLOSED_INSPECTIONS_REQUEST_CODE,
    INSPECTIONS_LIST_REQUEST_CODE,
    STATE_LEVEL_FIELDS_REQUEST_CODE,
    MASTER_AREA_AND_ITEMS_REQUEST_CODE,
    REPORT_INGOING_LID_REQUEST_CODE,
    REPORT_OUTGOING_LID_REQUEST_CODE,
    REPORT_ROUTINE_LID_REQUEST_CODE,
    REPORT_INGOING_REQUEST_CODE,
    REPORT_OUTGOING_REQUEST_CODE,
    REPORT_ROUTINE_REQUEST_CODE,
    REPORTS_REQUEST_CODE,
    UPDATE_REPORT_STATUS_REQUEST_CODE,
    CREATE_REPORT_REQUEST_CODE,
    UPLOAD_REPORT_REQUEST_CODE,
    DOWNLOAD_LID_PHOTO,
    UPLOAD_USER_SIGNATURE_REQUEST_CODE,
    DELETE_SIGNATURE_REQUEST_CODE,
    USER_DEVICE_INFORMATION_REQUEST_CODE,
    ISNPECTION_COORDINATES_REQUEST_CODE,
    PASSWORD_FORGET_REQUEST_CODE,
    EDIT_REPORT_REQUEST_CODE,
    COUNTRIES_STATES_REQUEST_CODE,
    SIGNUP_REQUEST_CODE,
    UPLOAD_DIAGNOSTIC_REQUEST_CODE,
    THEME_REQUEST_CODE,
    REPORT_FIELD_NAME_MAPPER_CODE,
    SUGGESTION_LIST_REQUEST_CODE,
    MOBILE_OTHER_FIELDS_REQUEST_CODE,
    UPLOAD_USER_PROFILE_PICTURE_REQUEST_CODE,
    PASSWORD_CHANGE_REQUEST_CODE
}
